simplenlp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("", include("wordy.urls")), path("admin/", admin.site.urls)]

wordy/urls.py
from django.urls import path

from . import views

urlpatterns = [path("", views.index, name="index")]

wordy/models.py
from collections import namedtuple

from django.db import models
from django.db.models import Sum
from nltk import FreqDist
from nltk.tokenize import word_tokenize, sent_tokenize

import wordy

ViewData = namedtuple(
    "ViewData", ["word", "count", "occurrence"]
)  # simple structure to store a summary of results


class Document(models.Model):
    """A document with full text, ready for ingestion."""

    name = models.SlugField(unique=True)
    full_text = models.TextField()

    def __str__(self):
        return self.name

    def ingest(self):
        """Perform natural language processing on this document and store the results. Previous results for this
        document are replaced."""

        # delete existing results
        WordResult.objects.filter(document=self).delete()

        # calculate word frequencies
        full_words = word_tokenize(self.full_text)
        frequencies = FreqDist(full_words)

        # accumulate samples for each word
        # we iterate by sentence to efficiently cover all samples
        results_by_word = {}
        for sentence in sent_tokenize(self.full_text):
            for word in word_tokenize(sentence):
                if (
                    word.isalpha()
                    and word.casefold() not in wordy.ENGLISH_STOP_WORDS
                    and word not in results_by_word
                ):
                    results_by_word[word] = WordResult(
                        name=word,
                        document=self,
                        count=frequencies[word],
                        sample=sentence,
                    )

        # store results with samples
        WordResult.objects.bulk_create(results_by_word.values())


class WordResult(models.Model):
    """Measurements for a single word in a single document."""

    name = models.SlugField()
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    count = models.IntegerField()
    sample = models.TextField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name="wordresult_name_document", fields=["name", "document"]
            )
        ]

    def __str__(self):
        return f"{self.name}.{self.document}: {self.count}"

    @classmethod
    def get_words_by_frequency(cls):
        """Generate results across all documents in dictionary format. Words are ordered by total count. Each entry
        includes a sample sentence from each document the word appears in."""

        # calculate total count by word across all documents
        # (descending order, exclude words with a count of 1)
        total_queryset = (
            WordResult.objects.values("name")
            .distinct()
            .annotate(total_count=Sum("count"))
            .filter(total_count__gt=1)
            .order_by("-total_count", "name")
        )

        # convert results to dictionary
        result = {}
        for item in total_queryset:
            name = item["name"]
            result[name] = ViewData(word=name, count=item["total_count"], occurrence={})

        # collect all distinct samples
        sample_queryset = WordResult.objects.values(
            "name", "document__name", "sample"
        ).order_by("name", "document__name")

        # add samples to results
        for item in sample_queryset:
            name = item["name"]
            document = item["document__name"]

            if name in result.keys():
                result[name].occurrence[document] = item["sample"]

        return result

wordy/forms.py
from django import forms


class UploadForm(forms.Form):
    document_file = forms.FileField(label="")

wordy/views.py
from django.core.files.uploadedfile import UploadedFile
from django.shortcuts import render
from django.utils.text import slugify

from .forms import UploadForm
from .models import Document, WordResult


def handle_upload(f: UploadedFile):  # pragma: no cover
    """Store uploaded file as a document. Existing documents (determined by filename) are overwritten.
    Non-text files are rejected."""

    if f.content_type != "text/plain":
        raise NotImplementedError(
            f"Filetype not handled. Please upload a text/plain file."
        )

    name = slugify(f.name.replace(".txt", ""))
    content = f.read().decode(
        "utf-8"
    )  # we assume small files, so we don't use f.chunk()

    existing_queryset = Document.objects.filter(name__exact=name)

    # create new document, or overwrite existing one
    if len(existing_queryset) == 0:
        document = Document(name=name, full_text=content)
    else:
        document = existing_queryset[0]
        document.full_text = content

    document.save()

    # process document
    try:
        document.ingest()
    except LookupError:
        raise LookupError(
            "LookupError while running ingest function. Did you run initwordy before starting the site?"
        )


def index(request):  # pragma: no cover
    """On GET, generate app form and results. On POST, process the uploaded text file."""

    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            handle_upload(request.FILES["document_file"])

    form = UploadForm()  # reset form
    words_by_frequency = WordResult.get_words_by_frequency()
    context = {"form": form, "word_by_frequency": words_by_frequency}

    return render(request, "wordy/index.html", context)

wordy/templates/wordy/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Wordy analysis</title>

    <style>
        body {font-family: sans-serif;}

        h1, h2, form, table {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        #wordy {
            border-collapse: collapse;
        }

        #wordy caption {
            font-weight: bold;
            font-size: large;
            color: #333;
            padding: 0.5em;
        }

        #wordy td, #wordy th {
            border: 1px solid #ddd;
            padding: 0.5em;
            vertical-align: text-top;
            text-align: left;
        }

        #wordy tr:nth-child(even) {background-color: #f2f2f2;}

        #wordy tr:hover {background-color: #ddd;}

        #wordy th {
            padding-top: 0.5em;
            padding-bottom: 0.5em;
            background-color: #04AA6D;
            color: white;
        }

        input#id_document_file {
            border: none;
            border-radius: 0.5em;
            background-color: #f2f2f2;
            padding: 1em;
        }

        input#submit {
            border: none;
            border-radius: 0.5em;
            background-color: #04AA6D;
            color: white;
            font-weight: bold;
            padding: 1em;
        }

    </style>
</head>

<body>

<h1>Wordy analysis</h1>

<h2>Add document</h2>

<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form }}
    <input id="submit" type="submit" value="Upload">
</form>

<h2>Results</h2>

<table id="wordy">
    <caption>Interesting words by frequency</caption>
    <thead>
        <tr>
            <th scope="colgroup">Count</th>
            <th scope="colgroup">Word</th>
            <th scope="colgroup">Samples</th>
        </tr>
    </thead>

    <tbody>
        {% for word, result in word_by_frequency.items %}
            <tr>
                <td>{{ result.count }}</td>
                <td>{{ word }}</td>
                <td>
                    {% for document, sample in result.occurrence.items %}
                        <p title="{{ sample }}">{{ sample|truncatechars:20 }} ({{ document }})</p>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </tbody>

</table>

</body>
</html>